/*
 * Copyright (C) 2025 The halogenOS Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.android.internal.util;

import android.app.ActivityTaskManager;
import android.app.Application;
import android.app.TaskStackListener;
import android.content.ComponentName;
import android.content.Context;
import android.os.Build;
import android.os.Bundle;
import android.os.Process;
import android.os.SystemProperties;
import android.provider.Settings;
import android.text.TextUtils;
import android.util.Log;

import java.lang.reflect.Field;
import java.util.Arrays;
import java.util.List;
import java.util.Map;

/**
 * SimplePropImitation - Simplified property imitation for GMS
 * @hide
 */
public class SimplePropImitation {

    private static final String TAG = "SimplePropImitation";
    private static final boolean DEBUG = Log.isLoggable(TAG, Log.DEBUG);

    private static final String PACKAGE_GMS = "com.google.android.gms";
    private static final String PACKAGE_FINSKY = "com.android.vending";
    private static final String PROCESS_GMS_UNSTABLE = PACKAGE_GMS + ".unstable";

    // GMS Add Account Activity - we need to skip imitation when this is on top
    private static final ComponentName GMS_ADD_ACCOUNT_ACTIVITY = ComponentName.unflattenFromString(
            "com.google.android.gms/.auth.uiflows.minutemaid.MinuteMaidActivity");

    // Build field name → system property name mapping
    private static final Map<String, String> FIELD_TO_SYSPROP = Map.ofEntries(
            Map.entry("PRODUCT", "ro.product.name"),
            Map.entry("DEVICE", "ro.product.device"),
            Map.entry("MANUFACTURER", "ro.product.manufacturer"),
            Map.entry("BRAND", "ro.product.brand"),
            Map.entry("MODEL", "ro.product.model"),
            Map.entry("FINGERPRINT", "ro.build.fingerprint"),
            Map.entry("HARDWARE", "ro.hardware"),
            Map.entry("ID", "ro.build.id"),
            Map.entry("TYPE", "ro.build.type"),
            Map.entry("TAGS", "ro.build.tags"),
            Map.entry("VERSION.INCREMENTAL", "ro.build.version.incremental"),
            Map.entry("VERSION.RELEASE", "ro.build.version.release"),
            Map.entry("VERSION.SECURITY_PATCH", "ro.build.version.security_patch"),
            Map.entry("VERSION.DEVICE_INITIAL_SDK_INT", "ro.product.first_api_level")
    );

    // Hardware-identity system properties whose android.os.Build.* Java static
    // must ALSO be reflected. These props are supplied as raw SYSPROP.* overlay
    // items (real akita values from the factory image) and spoofed at the native
    // level, but their Build statics were frozen at class-load from the real
    // device props. The integrity probe can read Build.HARDWARE/BOARD/SOC_MODEL/
    // SOC_MANUFACTURER via Java/reflection, which the native spoof does not
    // cover — so mirror the spoofed value into the Java field too.
    private static final Map<String, String> SYSPROP_TO_BUILD_FIELD = Map.ofEntries(
            Map.entry("ro.hardware", "HARDWARE"),
            Map.entry("ro.product.board", "BOARD"),
            Map.entry("ro.soc.model", "SOC_MODEL"),
            Map.entry("ro.soc.manufacturer", "SOC_MANUFACTURER")
    );

    // Product property suffix for fields that have partition variants
    private static final Map<String, String> PRODUCT_PROP_SUFFIX = Map.of(
            "PRODUCT", "name",
            "DEVICE", "device",
            "MANUFACTURER", "manufacturer",
            "BRAND", "brand",
            "MODEL", "model"
    );

    // Partition prefixes for product properties that the integrity probe reads
    // via native code
    private static final String[] PARTITION_PREFIXES = {
            "ro.product.vendor.", "ro.product.system.",
            "ro.product.odm.", "ro.product.system_ext.",
    };

    // Overlay item prefixes. Beyond the "FIELD:value" Build.* entries, the
    // overlay carries the real verified-boot values from the claimed device's
    // factory image (generated by the EvilIntegrity updater):
    //   SYSPROP.<name>:<value>  - a raw system property, applied verbatim
    //   ATTEST.<name>:<value>   - an attestation-only value with no real
    //                             sysprop, stashed for KeyboxImitationHooks
    private static final String RAW_SYSPROP_PREFIX = "SYSPROP.";
    private static final String ATTEST_PREFIX = "ATTEST.";
    private static final String ATTEST_VBOOT_KEY = "ATTEST.VBOOT_KEY";
    private static final String PROP_VBMETA_DIGEST = "ro.boot.vbmeta.digest";

    private static volatile List<String> sCertifiedProps = null;
    // Real verified-boot values sourced from the overlay, consumed by
    // KeyboxImitationHooks to fill the attestation RootOfTrust so the forged
    // cert agrees with the spoofed ro.boot.vbmeta.digest prop (invent once,
    // use twice). Null until the certified props are applied in this process.
    private static volatile String sVerifiedBootKey = null;
    private static volatile String sVerifiedBootHash = null;
    private static volatile String sProcessName = "";
    private static volatile boolean sSupportsHardwareAttestation = false;
    // Cached at first setProps() call, BEFORE any sysprop spoofing is applied.
    // True when spoofing should run — i.e. ro.boot.verifiedbootstate is anything
    // other than "green". On orange (unlocked) AVB is bypassed entirely; on
    // yellow our test key signed vbmeta but Google does not trust it as an OEM
    // root, so the attestation chain Google sees still needs the same spoof
    // treatment. Only green (Spacewar-style, real OEM-trusted key) bypasses it.
    private static volatile boolean sShouldSpoof = false;
    private static volatile boolean sBootStateChecked = false;
    // True only in the processes we deliberately spoof for Play Integrity — GMS
    // and Finsky (the Play Store). The keybox attestation forge is gated on this
    // (via isSpoofTarget) so every OTHER app gets its normal keystore behaviour.
    private static volatile boolean sSpoofTarget = false;

    private static native void nativeSpoofSysProp(String name, String value);
    private static native void nativeEnableSysPropSpoof();

    private SimplePropImitation() {
    }

    /**
     * Set properties for the given context.
     * This is called from Instrumentation when a new application is created.
     */
    public static void setProps(Context context) {
        final String packageName = context.getPackageName();
        final String processName = Application.getProcessName();

        if (TextUtils.isEmpty(packageName) || TextUtils.isEmpty(processName)) {
            Log.e(TAG, "Null package or process name");
            return;
        }

        sProcessName = processName;

        // Read the real bootloader state BEFORE any spoofing is applied. This
        // value gets cached and consumed by KeyboxImitationHooks too — once
        // we spoof ro.boot.verifiedbootstate to "green", a later
        // SystemProperties.get would return the spoofed value.
        if (!sBootStateChecked) {
            String bootState = SystemProperties.get("ro.boot.verifiedbootstate", "");
            boolean isGreen = "green".equals(bootState);
            // User toggle gates the whole spoofing layer. Defaults to enabled
            // so existing installs keep working; the Settings UI exposes the
            // switch under Apps. Read once per process — runtime toggling
            // takes effect for newly started apps only.
            boolean userEnabled = Settings.Secure.getInt(
                    context.getContentResolver(),
                    Settings.Secure.ATTESTATION_SPOOF_ENABLED, 1) != 0;
            // Spoof on anything except green: orange (no AVB) and yellow (AVB
            // with a custom key Google does not recognise as an OEM root) both
            // need the full prop + keybox spoof to pass Play Integrity. The
            // user toggle can disable the path regardless on orange/yellow.
            sShouldSpoof = !isGreen && userEnabled;
            sSupportsHardwareAttestation = isGreen;
            sBootStateChecked = true;
            Log.i(TAG, "verifiedbootstate=" + bootState
                    + " userEnabled=" + userEnabled
                    + " (shouldSpoof=" + sShouldSpoof + ")");
        }

        // Skip spoofing only when the bootloader is genuinely OEM-verified
        // (green). On orange and yellow the chain Google sees still doesn't
        // chain to a key it trusts, so we run the full spoof path.
        if (!sShouldSpoof) {
            Log.i(TAG, "Bootloader OEM-verified (green) — skipping prop spoofing for " + processName);
            nativeEnableSysPropSpoof();
            return;
        }

        // Only GMS and Finsky are spoof targets; the keybox forge keys off this.
        sSpoofTarget = PACKAGE_GMS.equals(packageName) || PACKAGE_FINSKY.equals(packageName);

        if (PACKAGE_GMS.equals(packageName)) {
            Log.i(TAG, "Spoofing props for " + processName);

            // We handle all GMS processes, but special handling for unstable
            if (PROCESS_GMS_UNSTABLE.equals(processName)) {
                setCertifiedPropsForGms(context);
            } else if (processName.startsWith(PACKAGE_GMS)) {
                loadAndSetCertifiedProps(context);
            }
        } else if (PACKAGE_FINSKY.equals(packageName)) {
            Log.i(TAG, "Spoofing props for " + processName);
            loadAndSetCertifiedProps(context);
        }

        // Lock the native spoof table for all processes
        nativeEnableSysPropSpoof();
    }

    /**
     * Special handling for GMS processes - checks for Add Account activity
     */
    private static void setCertifiedPropsForGms(Context context) {
        loadCertifiedProps(context);

        final boolean wasAddAccountOnTop = isGmsAddAccountActivityOnTop();

        // Register a task stack listener to detect when Add Account activity changes
        final TaskStackListener taskStackListener = new TaskStackListener() {
            @Override
            public void onTaskStackChanged() {
                final boolean isAddAccountOnTop = isGmsAddAccountActivityOnTop();
                if (isAddAccountOnTop ^ wasAddAccountOnTop) {
                    dlog("GmsAddAccountActivityOnTop is:" + isAddAccountOnTop 
                            + " was:" + wasAddAccountOnTop + ", killing myself!");
                    // Process will restart automatically later
                    Process.killProcess(Process.myPid());
                }
            }
        };

        if (!wasAddAccountOnTop) {
            dlog("Spoofing build for GMS");
            applyCertifiedProps();
        } else {
            dlog("Skip spoofing build for GMS, because GmsAddAccountActivityOnTop");
        }

        try {
            ActivityTaskManager.getService().registerTaskStackListener(taskStackListener);
        } catch (Exception e) {
            Log.e(TAG, "Failed to register task stack listener!", e);
        }
    }

    /**
     * Load and set certified props without checking for Add Account activity
     */
    private static void loadAndSetCertifiedProps(Context context) {
        loadCertifiedProps(context);
        applyCertifiedProps();
    }

    /**
     * Load certified properties from the caller-gated CorporateControlSatisfier
     * provider. The props no longer live in the framework-res resource table;
     * they are handed out synchronously through a ContentResolver.call() by the
     * priv-app that owns them.
     */
    private static void loadCertifiedProps(Context context) {
        if (sCertifiedProps != null) {
            return;
        }

        try {
            Bundle result = context.getContentResolver().call(
                    "custom.corporatecontrolsatisfier",
                    "obtainControlConformanceAttributes", null, null);
            String[] props = (result != null) ? result.getStringArray("attributes") : null;
            sCertifiedProps = (props != null) ? Arrays.asList(props) : Arrays.asList();
            dlog("Loaded " + sCertifiedProps.size() + " certified properties");
        } catch (Exception e) {
            Log.e(TAG, "Failed to load certified properties", e);
            sCertifiedProps = Arrays.asList();
        }
    }

    /**
     * Apply the certified properties
     */
    private static void applyCertifiedProps() {
        if (sCertifiedProps == null || sCertifiedProps.isEmpty()) {
            Log.e(TAG, "No certified props loaded");
            return;
        }

        Log.i(TAG, "Applying " + sCertifiedProps.size() + " certified props");
        String firstApiLevel = null;
        for (String entry : sCertifiedProps) {
            final String[] parts = entry.split(":", 2);
            if (parts.length != 2) {
                Log.e(TAG, "Invalid entry in certified props: " + entry);
                continue;
            }

            // Raw system property (real verified-boot values). Applied verbatim
            // at native level; not a Build.* field.
            if (parts[0].startsWith(RAW_SYSPROP_PREFIX)) {
                final String propName = parts[0].substring(RAW_SYSPROP_PREFIX.length());
                nativeSpoofSysProp(propName, parts[1]);
                // Mirror hardware-identity props into their android.os.Build Java
                // static, which the native spoof cannot reach (see map comment).
                final String buildField = SYSPROP_TO_BUILD_FIELD.get(propName);
                if (buildField != null) {
                    setPropValue(buildField, parts[1]);
                }
                // The vbmeta digest doubles as the attestation verifiedBootHash:
                // remember it so the forged cert and the prop agree.
                if (PROP_VBMETA_DIGEST.equals(propName)) {
                    sVerifiedBootHash = parts[1];
                }
                continue;
            }
            // Attestation-only value with no real sysprop (verified-boot key).
            if (parts[0].startsWith(ATTEST_PREFIX)) {
                if (ATTEST_VBOOT_KEY.equals(parts[0])) {
                    sVerifiedBootKey = parts[1];
                }
                continue;
            }

            setPropValue(parts[0], parts[1]);
            if ("VERSION.DEVICE_INITIAL_SDK_INT".equals(parts[0])) {
                firstApiLevel = parts[1];
            }
            // Spoof the primary system property at native level
            final String sysProp = FIELD_TO_SYSPROP.get(parts[0]);
            if (sysProp != null) {
                nativeSpoofSysProp(sysProp, parts[1]);
            }
            // For product properties, also spoof all partition variants
            final String suffix = PRODUCT_PROP_SUFFIX.get(parts[0]);
            if (suffix != null) {
                for (String prefix : PARTITION_PREFIXES) {
                    nativeSpoofSysProp(prefix + suffix, parts[1]);
                }
                nativeSpoofSysProp("ro.product." + suffix + "_for_attestation", parts[1]);
                // Build.<X>_FOR_ATTESTATION is a static final field initialised
                // from ro.product.<x>_for_attestation at Build class load time —
                // long before our JNI sysprop spoof is active. AndroidKeyStore
                // attestation reads Build.<X>_FOR_ATTESTATION directly (preferred
                // over Build.<X>), so we must reflectively overwrite the cached
                // field too, otherwise keystore2 gets the real device IDs in
                // ATTESTATION_ID_* and Google's PI server rejects as inconsistent.
                setPropValue(parts[0] + "_FOR_ATTESTATION", parts[1]);
            }
        }

        // Spoof boot attestation properties (migrated from system/core init)
        nativeSpoofSysProp("ro.boot.flash.locked", "1");
        nativeSpoofSysProp("ro.boot.verifiedbootstate", "green");
        nativeSpoofSysProp("ro.boot.veritymode", "enforcing");
        nativeSpoofSysProp("ro.boot.vbmeta.device_state", "locked");

        // The AVB/dm-verity digest properties (ro.boot.vbmeta.* and
        // partition.<name>.verified.*) are supplied as SYSPROP.* overlay items
        // above, carrying the REAL values read from the claimed device's
        // factory image. A stock locked device populates these, and they must
        // be internally consistent with the spoofed Pixel fingerprint and the
        // green/locked state — an empty or XOS-specific set is the silent
        // reject channel we previously observed. On an unlocked bootloader
        // libavb leaves them absent, so if the overlay omits them (older
        // updater) nothing here re-introduces a mismatch.

        // Spoof the properties the integrity probe reads.
        // ro.product.first_api_level is already spoofed via FIELD_TO_SYSPROP, but
        // ro.board.first_api_level / ro.vendor.api_level are read too. Force them
        // to the claimed device's launch API, otherwise the board/vendor props
        // leak the real device's launch API alongside the spoofed product
        // first_api_level — an internal inconsistency a stock device never has. NOTE: ro.board.api_level is deliberately NOT forced
        // here — it is NOT a launch API but the vendor image's API level (a YYYYMM
        // value, e.g. 202504 for akita), supplied with its real per-device value
        // by the certified-props overlay (SYSPROP.ro.board.api_level extracted
        // from the factory image). Forcing it to the launch API here would both
        // be wrong and shadow the overlay's correct value.
        if (firstApiLevel != null) {
            nativeSpoofSysProp("ro.vendor.api_level", firstApiLevel);
            nativeSpoofSysProp("ro.board.first_api_level", firstApiLevel);
        }
        nativeSpoofSysProp("ro.revision", "");
        nativeSpoofSysProp("init.svc.adbd", "stopped");
        nativeSpoofSysProp("persist.sys.usb.config", "none");
        nativeSpoofSysProp("sys.usb.config", "none");

        // Spoof build fingerprint across all partition variants
        String fp = Build.FINGERPRINT;
        if (fp != null && !fp.isEmpty()) {
            for (String partition : new String[]{
                    "vendor", "system", "system_ext", "odm", "bootimage"}) {
                nativeSpoofSysProp("ro." + partition + ".build.fingerprint", fp);
            }
        }

        // Hide custom-ROM identity props. The probe reads system properties
        // directly, and these announce the ROM (and the maintainer) outright —
        // e.g. ro.custom.version = "halogenOS_<device>-...-UNOFFICIAL". Empty
        // them so a native read reveals nothing.
        for (String p : new String[]{
                "ro.custom.version",
                "ro.custom.build.version",
                "ro.custom.build.version.sp",
                "ro.custom.build_type",
                "ro.custom.display.version",
                "ro.custom.build.device.maintainer"}) {
            nativeSpoofSysProp(p, "");
        }

        // Stock build-identity props that otherwise still carry the REAL device
        // (aosp_<device>-user / qssi-user ... <real BUILD_ID>) instead of the
        // claimed Pixel, contradicting the spoofed fingerprint. Rebuild them from
        // the already-spoofed Build fields so a native read stays consistent.
        // ro.build.user is forced to the AOSP release-build value ("android-build")
        // since the real one leaks the build environment.
        nativeSpoofSysProp("ro.build.flavor", Build.PRODUCT + "-" + Build.TYPE);
        nativeSpoofSysProp("ro.build.description",
                Build.PRODUCT + "-" + Build.TYPE + " " + Build.VERSION.RELEASE
                + " " + Build.ID + " " + Build.VERSION.INCREMENTAL + " " + Build.TAGS);
        nativeSpoofSysProp("ro.build.user", "android-build");

        // Diagnostic dump. Visible to us via adb/root; the spoofed process is
        // untrusted_app and cannot read logcat, so the inspected app never sees it.
        Log.i(TAG, "Build.FINGERPRINT = " + Build.FINGERPRINT);
        Log.i(TAG, "Build.PRODUCT = " + Build.PRODUCT);
        Log.i(TAG, "Build.DEVICE = " + Build.DEVICE);
        Log.i(TAG, "Build.MANUFACTURER = " + Build.MANUFACTURER);
        Log.i(TAG, "Build.BRAND = " + Build.BRAND);
        Log.i(TAG, "Build.MODEL = " + Build.MODEL);
        Log.i(TAG, "Build.ID = " + Build.ID);
        Log.i(TAG, "Build.TYPE = " + Build.TYPE);
        Log.i(TAG, "Build.TAGS = " + Build.TAGS);
        Log.i(TAG, "Build.VERSION.INCREMENTAL = " + Build.VERSION.INCREMENTAL);
        Log.i(TAG, "Build.VERSION.RELEASE = " + Build.VERSION.RELEASE);
        Log.i(TAG, "Build.VERSION.SECURITY_PATCH = " + Build.VERSION.SECURITY_PATCH);
        Log.i(TAG, "Build.VERSION.DEVICE_INITIAL_SDK_INT = "
                + Build.VERSION.DEVICE_INITIAL_SDK_INT);
        Log.i(TAG, "Build.HARDWARE = " + Build.HARDWARE);
        Log.i(TAG, "Build.BOARD = " + Build.BOARD);
        Log.i(TAG, "Build.SOC_MODEL = " + Build.SOC_MODEL);
        Log.i(TAG, "Build.SOC_MANUFACTURER = " + Build.SOC_MANUFACTURER);
    }

    /**
     * Set a single property value using reflection
     */
    private static void setPropValue(String key, String value) {
        try {
            dlog("Setting prop " + key + " to " + value);

            Class<?> clazz = Build.class;
            String fieldName = key;

            if (key.startsWith("VERSION.")) {
                clazz = Build.VERSION.class;
                fieldName = key.substring(8);
            }

            Field field = clazz.getDeclaredField(fieldName);
            field.setAccessible(true);

            // Cast the value to int if it's an integer field, otherwise string
            if (field.getType().equals(Integer.TYPE)) {
                field.set(null, Integer.parseInt(value));
            } else {
                field.set(null, value);
            }

            field.setAccessible(false);
        } catch (Exception e) {
            Log.e(TAG, "Failed to set prop " + key, e);
        }
    }

    /**
     * Check if GMS Add Account activity is on top
     */
    private static boolean isGmsAddAccountActivityOnTop() {
        try {
            final ActivityTaskManager.RootTaskInfo focusedTask =
                    ActivityTaskManager.getService().getFocusedRootTaskInfo();
            return focusedTask != null && focusedTask.topActivity != null
                    && GMS_ADD_ACCOUNT_ACTIVITY.equals(focusedTask.topActivity);
        } catch (Exception e) {
            Log.e(TAG, "Unable to get top activity!", e);
        }
        return false;
    }

    /**
     * Whether the device has a locked bootloader and supports hardware attestation.
     * When true, spoofing is unnecessary — stock behavior suffices.
     */
    public static boolean supportsHardwareAttestation() {
        return sSupportsHardwareAttestation;
    }

    /**
     * True when spoofing should run, i.e. ro.boot.verifiedbootstate is not
     * "green". Orange (unlocked) and yellow (locked with a non-OEM key) both
     * return true because, in either case, Google's Play Integrity backend
     * does not trust the device's native attestation chain and the full prop
     * + keybox spoof is required. Captured at the first setProps() call,
     * before any sysprop spoofing.
     */
    public static boolean shouldSpoof() {
        return sShouldSpoof;
    }

    /**
     * True only when the current process is a package we deliberately spoof for
     * Play Integrity — GMS or Finsky (Play Store) — and spoofing is active
     * (non-green bootloader, user-enabled). The keybox attestation forge runs
     * ONLY for these targets; every other app keeps its normal keystore
     * behaviour, so an unrelated app doing its own key attestation still sees the
     * device's true state rather than a Pixel it plainly isn't.
     */
    public static boolean isSpoofTarget() {
        return sShouldSpoof && sSpoofTarget;
    }

    /**
     * The real verified-boot key hash (hex) for the claimed device, sourced
     * from the overlay, or {@code null} if certified props have not been
     * applied in this process. Consumed by KeyboxImitationHooks to fill the
     * attestation RootOfTrust's verifiedBootKey.
     */
    public static String getVerifiedBootKey() {
        return sVerifiedBootKey;
    }

    /**
     * The real verified-boot hash (hex) for the claimed device — the same
     * value published as ro.boot.vbmeta.digest — or {@code null} if certified
     * props have not been applied in this process. Consumed by
     * KeyboxImitationHooks to fill the attestation RootOfTrust's
     * verifiedBootHash so the cert agrees with the prop.
     */
    public static String getVerifiedBootHash() {
        return sVerifiedBootHash;
    }

    /**
     * Debug logging
     */
    private static void dlog(String msg) {
        if (DEBUG) {
            Log.d(TAG, "[" + sProcessName + "] " + msg);
        }
    }
}
